[package]
name = "math_util"
version = "0.1.0"
authors = ["Woyten <woyten.tielesch@online.de>"]

[dependencies]
lazy_static = "*"
nalgebra = "*"
num = "*"
rayon = "*"
rustfft = "*"
thread_local = "*"
